name: GitHub Actions

on:
  - push

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Install dependencies
        run: make install
      - name: Run linter
        run: make lint
      - name: Code Coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: 924b9ec5c9489a4777e9f8b1f8fa6a2ba1de29d217b6e07af098e2f3c11d5ca1
        with:
          coverageCommand: make test-coverage
          debug: true
